### PR TITLE
Replaced goofy character in menu string.

### PR DESCRIPTION
**Pull request by hjr**
Brief summary of the changes
----------------------------

Minimal fix of some french non ascii character slipped into some GUI string.

### CODE REVIEW

**Review by lordfolken — CHANGES_REQUESTED** [review]
This is used as a string match in translations. If we change it it needs to be changed in all occurrences.

**Comment by hjr** [comment]
That is correct, but the typo is actually visible for English and makes just no sense. All translations will stay the same and it is just a mechanical Ok click for the given suggestion from the translation AI system to get the translations aligned again. It is just a sooner or later...

**Comment by MaxKellermann** [comment]
fee707de890dc3d3d17d579696b1506b68a57d36

**Comment by hjr** [comment]
Ok, thx!

**Pull request closed without merging**
