### PR TITLE
Updated Manual (German) - Description of waypointdetails file, its structure and its usage for displaying text and media.

### LINKED ISSUE #242: Describe Waypoint_Details file format in XCSoar User Manual
The documentation does not describe the waypoint_details file anywhere. 

The Format is currently: 
[WAYPOINT_NAME] <- must match way point in cup
Text Text
Multiline <= appears in the description field and as long text on the following way-point page
file=/relative/url/to/xcsoardata=*.jpg <= clickable file to open with default associated picture viewer
file=/relative/url/to/xcsoardata=*.pdf <= clickable file to open with default associated image viewer
image=/relative/url/to/xcsoardata/*.png image displayed with zoom etc.

### PR DESCRIPTION
**Pull request by Buzz33**
Brief summary of the changes
----------------------------

This is an update for the German manual, chapter 04, 11, 12 and "installation", to describe the structure and functionality of the "waypointdetails" file ("Wegpunktdetails" Datei).  An example  to describe a possible usage of pictures/media is included, with several screenshots from Android phones. Also some aspects of Android storage specialitys are mentioned - and, where I noticed it, some typos were fixed.

Testing the functionality of the Waypointdetails file was carried out with Samsung Galaxy Note2 (Android 4.4.2), Galaxy Grand Prime (Android 5.1.1) and Galaxy Note10+ (Android 11) with XCSoar versions 7.10, 7.8 and version 6.8.11. (No Kobo, no Windows testing).

When the manual is compiled, the index should be checked, that it updated in the correct way. (I am not sure whether I used the right terminy/structure in tex here)

Later, when the bug with the "file=" command is fixed (issue #390), the corresponding remark in chapter 12 can be deleted.

Related issues and discussions
------------------------------
#390 

Closes #242

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Don't submit PRs with merge commits.

**Comment by lordfolken** [comment]
Thank you for all the work. Please rebase your git branch on current master. (Read up on git pull --rebase). That way we don't mess up the git history. Also please be more descriptive in the git message. Ie doc/user manual: describe wp Details.

**Comment by lordfolken** [comment]
Also there seems to be an error in the latex code somewhere in the ci.

**Comment by Buzz33** [comment]
> 
> 
> Don't submit PRs with merge commits.

Sorry, as I am totally new to all of this maybe I misunderstood the Fetch upstream function in Github. And then I was not able to get rid of this commit anymore, sorry.  I hope that it did not mess up anything else. 

Will you have to delete/close this PR now and I have to do the whole thing again with a new fork?

> Please rebase your git branch on current master. (Read up on git pull --rebase). That way we don't mess up the git history.

Thats the function I already searched,  thanks :-)
But before I will start it: How can I get rid of the Merge branch commit I made by fault? Will this disturb the correct rebase action or will it be resolved with the rebase function?

> Also please be more descriptive in the git message. Ie doc/user manual: describe wp Details.

Do you mean the text in the issue #242 message? I can edit the message in the way I described the PR, if thats ok? 

> 
> 
> Also there seems to be an error in the latex code somewhere in the ci.

CI=Coded Information?
Do you have any idea where or what I should search for?

**Comment by lordfolken** [comment]
Fixing your git history:
go back to
e922899 
(git checkout 
e922899)
Then git cherry-pick the other ones without the merge request.
Once that is done, do a git pull --rebase. Fix potential conflicts. 
at the end do a git push --force to this branch again. That way all the history should be there without the merge. 

To the git commits: "update chapter x" isn't  very descriptive, so that is what i wanted. but that is i think futile at this point
https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

CI: Continous Integration. Its the check here at the bottom of the PR, that tries to compile your changes. There is an error somewhere and the manuals aren't built correctly. You can check the logs of the failing check.

**Comment by Buzz33** [comment]
Thanks for your advise - but I am stuck here now. After even more hours of reading, trying things out within github desktop (I am not familiar with git, nor with the commandline things) and searching for errors in the logs there was no effort.
Cherry picked e922899, (the last commit  before the merge commit), cherry picked the other commits to the new branch - without the merge commit. Was ok so far. In the new branch the merge commit finally was in the history no more.  But rebasing this branch was not possible, just rebase with master. And after that, the merge commit was there again - in both branches. Maybe I dont understand all this right, maybe we talk not the same language, maybe.... seems not to be my business. 

Same with the logs: I searched it even before, searched all logs I could find today again, downloaded the raw log...
The only "error" I found there was: "2021-07-24T20:21:01.6168721Z make: *** [build/manual.mk:164: output/manual/XCSoar-manual-de.pdf] Error 1"

I think have to pause my work on this now due to other pressure, sorry :-/

**Comment by Buzz33** [comment]
Back to this...

History of my master branch locks strange, I am not sure what happened to it. I will not mess up things any more (i.e. by force pushing anything), so I better will delete it and use a new branch for a new PR. 
Will it be better to close/delete this PR before I delete the old master?
(I will wait with deleting my master branch until I get your "ok".)

I already made a new branch with the relevant cherry picked commits, squashed them per chapter, so history is readable and clear now. I will do a new PR with that one, if this is ok for you. 

For the error: I did not find anything so far but a line with unnecessary ####.... I deleted that one.

**Comment by Buzz33** [comment]
I will close this without merge and try a new one.

**Comment by Buzz33** [comment]
To Lordfolken:

I cherry picked and squashed chapters into a new branch in different ways, rebased these to master, started to create a new pull request - but what happens in Github Desktop history seems not to be logic in any way (bug??).

So I would delete this fork completely, to not mess up anything.

Or could someone else with more Latex and Git experience bring this to fruition?

**Pull request closed without merging**
