### PR TITLE
Added the CoPilot to the logger Settings

### PR DESCRIPTION
**Pull request by Luap-Paul**
next try, hope my pull request is now in a better shape.

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Don't update `po/`.
Where's the code for loading the configured setting from the profile?

**Comment by MaxKellermann** [comment]
Build failure:
```
test/src/RunIGCWriter.cpp:51:56: error: too few arguments to function call, expected 9, have 8
                     _T("MM"), "FOO", driver_name, true);
```

**Comment by MaxKellermann** [comment]
Say when you're done fixing all the problems.

**Comment by Luap-Paul** [comment]
alright!

**Pull request merged**
