### PR TITLE
Manual: En: Introduction: Update: Platforms, etc.

### PR DESCRIPTION
**Pull request by mlep**
Trying to update the status of current platform able to run XCSoar.
Please, edit as needed.

### CODE REVIEW

**Comment by MaxKellermann** [comment]
This PR removes the forum and later adds it. These commits should not be merged, please remove them from your branch.

**Comment by mlep** [comment]
I do not know how to remove them from my branch (I used the github website for my push request). Help appreciated.

**Comment by lordfolken** [comment]
@melp have a look here: https://medium.com/collaborne-engineering/git-branches-rewriting-history-and-avoiding-nightmares-part-1-b76f334f142c

**Comment by mlep** [comment]
@lordfolken: thank you for the pointer. However, the learning of git in command-line is quite steep. And not using it in other projects, I prefer to stick with the github interface. I could not find how to rebase my PR within github (I believe it is not possible). Please, provide me with a solution.

**Comment by DanD222** [comment]
@mlep: you could try using Git GUI clients like Git Kraken, for example.

**Comment by mlep** [comment]
Thank you @DanD222 for your suggestion. But it seems I have messed up my branch...
So, I am closing this PR and opening a new one.

**Pull request closed without merging**
