### PR TITLE
move IsCharDev() utility function to common assets for reusability

### PR DESCRIPTION
**Pull request by iltis42**
Brief summary of the changes
----------------------------
We need the IsCharDev() utility as already present in TTYPort also in the TTYEnumerator, so we move this one liner to generic assets. Next step, once this is merged, will be reusing this code in TTYEnumerator to solve #1012 

Related issues and discussions
------------------------------
#1012

### CODE REVIEW

**Comment by MaxKellermann** [comment]
This is the wrong place. `Asset.hpp` is a library which provides basic information about the device XCSoar runs on, and it has nothing to do with the filesystem. And I don't like that you add a include dependency to a public header.
A good place might be `system/FileUtil.cpp` which already has similar `stat()` wrappers.

**Comment by MaxKellermann** [comment]
You should rebase, but never merge into a PR branch.

**Comment by MaxKellermann** [comment]
There's still this merge commit, and it's utterly broken. The CI build will fail again.

**Comment by MaxKellermann** [comment]
There are now 6 commits in this PR, 2 of which are merge commits, and the rest is broken for other reasons. There should only be 1 commit.

**Comment by MaxKellermann** [comment]
... and now there are 7 broken commits, 3 of which are merge commits :-)

**Comment by iltis42** [comment]
need to rebase first, somehow local repo is messed up, and create a new one.

**Comment by MaxKellermann** [comment]
Closing this PR is yet more extra work for you. You can rebase without closing/opening new PR.

**Comment by iltis42** [comment]
> Closing this PR is yet more extra work for you. You can rebase without closing/opening new PR.

Yeah correct, now #1035 looks better, had messed up the #1034, somehow this could not rebase from the start as of local changes (?!) even after a stash and could not figure out, so reset head to master and created a fresh branch what was straightforward with exact the changesets we need and no merge.

**Pull request closed without merging**
