### PR TITLE
Preserve zoom level in TrafficWidget

### LINKED ISSUE #455: Flarm page defaults to 2 km range when switching pages
XCSoar versions having and not having the problem
-------------------------------------------------
Which XCSoar version are you using when seeing the problem? latest stable and experimental versions
Which XCSoar version is the last one you know that did not show the problem? no version

Expected behavior
-----------------
 I would expect the Flarm page to stay on the latest zoom factor when I return to the flarm page after switching to another page. 

Actual behavior
---------------
When I set flarm zoom pag at 10 km and switch afterwards to another page, and then subsequently return to the Flarm page the zoom factor is back at 2 km default value.

Steps to reproduce the behavior
-------------------------------
a. setting Flarm page zoom at 10 km
b. switching page from Flarm to another page i.e. cruising,
c. returning to Flarm page, zoom fgactor is now suddenly 2 km default again

Do you have any idea what may have caused this?
-----------------------------------------------
no

Do you have an idea how to solve the issue?
-------------------------------------------
no

### PR DESCRIPTION
**Pull request by zinuzoid**
Brief summary of the changes
----------------------------
Preserver zoom level in FLARM radar when switching between pages
flarm

Related issues and discussions
------------------------------
Closes #455

### CODE REVIEW

**Review by lordfolken — COMMENTED** [review]
Does this survive the warning_mode logic? In warning mode XCsoar forces the zoom to 2km.

**Comment by zinuzoid** [comment]
> Does this survive the warning_mode logic? In warning mode XCsoar forces the zoom to 2km.

Not sure, any suggestion how to reproduce that?

**Comment by lordfolken** [comment]
So finally. in #925 there is a file for replaying flarm traffic. That way you can test. 
However I'm pretty sure that the alarm mode sets the zoom to 2 km.

**Comment by lordfolken** [comment]
make output/UNIX/bin/FeedMEA
FeedNMEA tcp 4345 < pflaf01.txt

You find the file in the tests folder.

**Pull request closed without merging**
