### PR TITLE
Driver RIDIMUIM

### PR DESCRIPTION
**Pull request by alberiolima**
New ridimuim driver, and correct OAT GTAltimeter

### CODE REVIEW

**Comment by Turbo87** [comment]
unfortunately the XCSoar maintainer is not a big fan of GitHub and doesn't like pull requests like this. please read https://github.com/XCSoar/XCSoar/blob/master/README#L35-L48 on how to submit it the official way.

**Comment by alberiolima** [comment]
No such list xcsoar-develxcsoar-devel@lists.sourceforge.net

**Comment by Turbo87** [comment]
https://lists.sourceforge.net/lists/listinfo/xcsoar-devel ?!

**Comment by alberiolima** [comment]
thanks

**Pull request closed without merging**
