### PR TITLE
Tcinfobox

### PR DESCRIPTION
**Pull request by lordfolken**

### CODE REVIEW

**Comment by lordfolken** [comment]
Headsup to @bomilkar

**Comment by bomilkar** [comment]
The failing check seems to come from:
src/Device/Util/NMEAWriter.cpp:26:3: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
I understand this, but I don't know why it blames me for src/Device/Util/NMEAWriter.cpp

**Comment by lordfolken** [comment]
Ah thats osx thats broken. Nothing wrong with these commits.

**Comment by bomilkar** [comment]
I don't understand where these 2 commits are suddenly coming from.
9e940f61e0dac7e498385dc9a481e5662e3ef7da
60367f210cb5f49ec6da3f7489d065d39dbff566
I wrote these ~4 years ago. How come they suddenly reappear?

**Comment by lordfolken** [comment]
I cherry picked them from a branch in your repo.

**Comment by bomilkar** [comment]
Thanks! Finally I can drop one of my private patches. 👍

**Pull request merged**
