### PR TITLE
Fix crash in python module's flight.path()

### PR DESCRIPTION
**Pull request by tpatja**
Brief summary of the changes
----------------------------
Fixed a crash in the python modules flight.path() method that I recently found when trying it out. Also made the python tests run with python 3.

Related issues and discussions
------------------------------
No related issues or discussions found. Seems not many people are using the python module.

### CODE REVIEW

**Comment by MaxKellermann** [comment]
This commit is confusing and hard to read because it mixes 4 things in one commit, 2 of which are described. Each commit should only contain one change.

**Comment by tpatja** [comment]
Hi Max. The PR is now split into 3 commits.

**Comment by MaxKellermann** [comment]
Thanks, much better. Your third commit changes the indentation of the Py_BuildValue call, which hides what this commit is really doing.

**Comment by tpatja** [comment]
Indentation issue fixed.

**Comment by MaxKellermann** [comment]
Thanks again!

**Comment by tpatja** [comment]
Contributing this small patch was the least I could do, given the huge amount of value XCSoar has given me for free over the years on my cross country soaring flights. Thank you for your hard work on XCSoar and happy holidays!

**Pull request merged**
