### PR TITLE
Added driver for ATR833

### PR DESCRIPTION
**Pull request by Steffen-Engel**
added SetFrequency functions, grabbed from head branch of XCSoar
Added SetFrequency Buttons in waypoint dialog, when frequency of a waypoint is available

### CODE REVIEW

**Comment by Turbo87** [comment]
Hi Steffen, please send pull requests directly to the xcsoar-dev mailing list. The current maintainer is not a fan of Github unforunately.

see https://github.com/XCSoar/XCSoar/blob/master/README#L35-L48

**Comment by Steffen-Engel** [comment]
Hi Tobias,

ok, but how shall I do this?

would be nice, if it would be well documented, what exactly is meant by "
Use this mailing list to submit patches or "git pull" requests."?




Am 05.05.2015 um 00:44 schrieb Tobias Bieniek <notifications@github.com<mailto:notifications@github.com>>:


Hi Steffen, please send pull requests directly to the xcsoar-dev mailing list. The current maintainer is not a fan of Github unforunately.

see https://github.com/XCSoar/XCSoar/blob/master/README#L35-L48

**Comment by Turbo87** [comment]
1. Subscribe yourself on the mailing list at https://lists.sourceforge.net/lists/listinfo/xcsoar-devel
2. Send a mail to the list with something like "Please pull my v6.7.x branch from https://github.com/Steffen-Engel/XCSoar.git" and a small description of what you changed and why

I just noticed that you developed that feature on the `v6.7.x` branch. That branch is "stable", meaning that it should only receive bugfixes. If you develop new feature you should use the `master` branch instead.

**Comment by Steffen-Engel** [comment]
Ok, I'll do that.

I am working on v6.7.x because the master branch is totally unstable. Nearly every second pull did lead to instable or crashing software. After some rounds of searching for the reason because I thought it is my stuff crashing XCSoar I just had no more time to always search for reasons.
In this case it would make sense to have a halfway stable branch to work on.


Ingenieurb�ro Engel
Am Schwarzen Berge 11
38112 Braunschweig

0176/84833835
Steffen.Engel@nutrimat.de

________________________________________
Von: Tobias Bieniek [notifications@github.com]
Gesendet: Dienstag, 5. Mai 2015 09:53
An: XCSoar/XCSoar
Cc: Steffen Engel
Betreff: Re: [XCSoar] Added driver for ATR833 (#38)

 1.  Subscribe yourself on the mailing list at https://lists.sourceforge.net/lists/listinfo/xcsoar-devel
 2.  Send a mail to the list with something like "Please pull my v6.7.x branch from https://github.com/Steffen-Engel/XCSoar.git" and a small description of what you changed and why

I just noticed that you developed that feature on the v6.7.x branch. That branch is "stable", meaning that it should only receive bugfixes. If you develop new feature you should use the master branch instead.

�

**Comment by Turbo87** [comment]
hmm, that is a bit surprising to me, because the quality and stability of the whole codebase is usually quite good. just be prepared for hearing about this branch thing when you post your pull request to the mailing list.

**Comment by Steffen-Engel** [comment]
Oh, I can change to the head branch, but then the mailing list will hear about the stability of this branch
Max will complain anyway...

it was really nearly always, that XCSoar did not work after a pull. skalines broken was one and the JTI_main the other. I gave up then and switched to v6.7.x

Ingenieurb�ro Engel
Am Schwarzen Berge 11
38112 Braunschweig

0176/84833835
Steffen.Engel@nutrimat.de

________________________________________
Von: Tobias Bieniek [notifications@github.com]
Gesendet: Dienstag, 5. Mai 2015 13:23
An: XCSoar/XCSoar
Cc: Steffen Engel
Betreff: Re: [XCSoar] Added driver for ATR833 (#38)

hmm, that is a bit surprising to me, because the quality and stability of the whole codebase is usually quite good. just be prepared for hearing about this branch thing when you post your pull request to the mailing list.

�

**Comment by staylo** [comment]
The master branch is usually very stable, so that's unusual. Check your
build environment (help is available at http://www.xcsoar.org/contact/ ),
but if you can compile the master branch correctly please ticket any issues
you have at http://bugs.xcsoar.org/newticket

Please check that the code is stable on the master branch on whatever
platforms available before submitting. Max is picky about code quality
issues and coding styles etc and can be terse in his replies, but XCSoar is
complex and time consuming to maintain, and those are the ways he reduces
the time required.

**Comment by Steffen-Engel** [comment]
Be sure, it was not, those two points were not ok and for sure it was not a stability issue of the build environment.

v6.7.x is stable, master sometimes not. The issue with JNI_Onload (sorry for the wrong name) was inherent and I could not work on the things I wanted to take care of so it switched to v6.7.x.

It was also known and I had no more to time to wait for a fix:

<apf> Looks like Shutdown() is currently not even called on Android
<apf> My xcsoar.log always finish with:
<apf> [2015-03-07T13:11:53Z] Failed to open airspace file:
/mnt/sdcard/XCSoarData/maps-apf/apf-ger-nl-be-hr.xcm/airspace.txt
<apf> In mgmain JNI_OnLoad

When master is stable, I will be happy to switch back...

Max is terse? Nice way to name it ;-)


Ingenieurbüro Engel
Am Schwarzen Berge 11
38112 Braunschweig

0176/84833835
Steffen.Engel@nutrimat.de

________________________________________
Von: Simon Taylor [notifications@github.com]
Gesendet: Dienstag, 5. Mai 2015 15:04
An: XCSoar/XCSoar
Cc: Steffen Engel
Betreff: Re: [XCSoar] Added driver for ATR833 (#38)

The master branch is usually very stable, so that's unusual. Check your
build environment (help is available at http://www.xcsoar.org/contact/ ),
but if you can compile the master branch correctly please ticket any issues
you have at http://bugs.xcsoar.org/newticket

Please check that the code is stable on the master branch on whatever
platforms available before submitting. Max is picky about code quality
issues and coding styles etc and can be terse in his replies, but XCSoar is
complex and time consuming to maintain, and those are the ways he reduces
the time required.

**Pull request closed without merging**
