### PR TITLE
added copilot into logger settings

### PR DESCRIPTION
**Pull request by Luap-Paul**
Hello together,

with this commits i included a copilot into the logger settings, now the IGC File created by XCSoar includes that Information and also an LXNano Logger can be declarated.
I wasnt working with a Remote depository so i didnt manage to commit all the changes together, because it is a minor feature i think that could be useful. Hope this time the pull request is better created, if not just give a hint and i will try to adjust it!

### CODE REVIEW

**Comment by MaxKellermann** [comment]
If your PR contains text, this means that your commit messages are bad.
And your commit messages do not exist - "Update <filename>" is not a commit message.
You made one commit per file, but that's wrong - each commit must be self-contained, must build and must improve XCSoar. The way you split the commits doesn't make any sense.
This PR can't be merged in the current form.

**Comment by MaxKellermann** [comment]
And the CircleCI check has failed.

**Comment by MaxKellermann** [comment]
Closed - so you're not interested in fixing the issues?

**Comment by Luap-Paul** [comment]
Yes im interested in fixing the problems but isnt it easier to fix them and then start a new pull request?

**Comment by MaxKellermann** [comment]
No.

**Comment by lordfolken** [comment]
Its clean work. You can rewrite the git history with instructions here: https://help.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message#amending-older-or-multiple-commit-messages

**Comment by MaxKellermann** [comment]
5 months with no progress - I fear this isn't going anywhere.

**Pull request closed without merging**
