### PR TITLE
Update cs.po

### PR DESCRIPTION
**Pull request by MikeBravo15**
Update of the Czech translation via Weblate

### CODE REVIEW

**Comment by MaxKellermann** [comment]
This commit reformats the file and changes translations at the same time. That way, it's impossible to see what has changed.

**Comment by MikeBravo15** [comment]
Sorry for inconvenience, it is my first attempt.  I used the .po export from Weblate XCSoar translation. As a begginer, do not know how to handle Weblate exports to Git. I can manually change entries one by one in the original file, problem with this approach is, that it is A LOT of changes and I am a little bit affraid to pork the file with some missing signs etc. Also all the advantages of Weblate translation are lost with manual edit. Can you please hint me the correct way? Thank you for your help

**Comment by MaxKellermann** [comment]
Don't export Weblate files. Weblate already integrates well with git. It's as simple as pulling from the Weblate git repository. If you do it manually, and don't do it 100% correctly, you break lots of things.

**Comment by MikeBravo15** [comment]
Thank you. In that case please disregard this attempt. Shall I do something on my side to update the translation on Git automatically from Weblate?

**Comment by MikeBravo15** [comment]
Hallo Max,
I hope I have found a correct way, how to export .po from Weblate (structure is the same as in Git). Shall I close this pull rqst and start from scratch?

**Comment by MikeBravo15** [comment]
New attempt, please review

**Comment by lordfolken** [comment]
> New attempt, please review

Better. But please do a force push to remove the initial bad commit.

**Comment by MaxKellermann** [comment]
None of this is necessary. All we need to do is pull from Weblate's git repository. Unfortunately, I don't have admin access to it, so I can't do it. Who does?

**Comment by orangesunny** [comment]
> None of this is necessary. All we need to do is pull from Weblate's git repository. Unfortunately, I don't have admin access to it, so I can't do it. Who does?

Hey, @MaxKellermann I made you an admin as you are one of the upstream maintainers 😉 
So far, @felixhaedicke was the only one there.
@MikeBravo15 thank you for the head’s up!

**Comment by MikeBravo15** [comment]
Thanks to all involved, can you please close this branch?

**Comment by MaxKellermann** [comment]
Thanks @orangesunny for dropping by!
All is merged, and weblate/GitHub are in sync again. Closing this PR, as it's obsolete.

**Pull request closed without merging**
