### PR TITLE
added copilot into logger settings N°2

### PR DESCRIPTION
**Pull request by Luap-Paul**
This is my second pull-request due to problems with my repository. 
I Added a field for an copilot to the logger settings, and expanded the LX Driver, so the declaration for the nano includes the copilot.

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Please clean up your branch. It contains a merge commit, which is not acceptable.

**Comment by MaxKellermann** [comment]
Please submit a new PR after you've fixed the obvious problems.

**Comment by Luap-Paul** [comment]
Hi Max,

 

all right, at the time im preparing for some exams so dont wonder if it takes some time.

Im not shure anymore, do you think it is usefull to integrate that function even if it just works with lx devices?

 

Paul

Gesendet: Freitag, 16. August 2019 um 12:02 Uhr
Von: "Max Kellermann" <notifications@github.com>
An: XCSoar/XCSoar <XCSoar@noreply.github.com>
Cc: Luap-Paul <paul.jenny@gmx.net>, Assign <assign@noreply.github.com>
Betreff: Re: [XCSoar/XCSoar] added copilot into logger settings N°2 (#229)


Please submit a new PR after you've fixed the obvious problems.

**Comment by MaxKellermann** [comment]
It is an interesting feature.

**Pull request closed without merging**
