### PR TITLE
Radio frequency infobox panel

### PR DESCRIPTION
**Pull request by roeles**
This branch modifies the existing radio infoboxes, and expands them with the option to manually modify the radio frequency that the infobox shows.

### CODE REVIEW

**Comment by roeles** [comment]
I'll re-arrange the commits a bit better before removing WIP

**Comment by mlep** [comment]
Please, could you also update the documentation?

**Comment by roeles** [comment]
@mlep 
> Please, could you also update the documentation?

Sure, no problem.
A few questions:

1. Would you mind if I do this in a separate commit?
2. Do you already have specific sections in mind that are affected by my changes?

**Comment by mlep** [comment]
I believe the most appropriate place is the chapter describing the Infoboxes (doc/en/ch10_infobox_reference.tex). Not sure about the section, though (the doc is a bit outdated on some parts).
Except if a lead developer prefers the same PR to be used, I guess a separate commit is fine.

**Comment by MaxKellermann** [comment]
Ideally, a commit which adds a new (user-visible) feature also contains the documentation (and NEWS line etc.)

**Comment by roeles** [comment]
Alright, I'll take a look at it.

**Comment by MaxKellermann** [comment]
Build failure on `TARGET=PC`:
```
src/InfoBoxes/Panel/RadioEdit.cpp: In constructor ‘RadioOffsetButtons::RadioOffsetButtons(bool)’:
src/InfoBoxes/Panel/RadioEdit.cpp:33:143: error: no matching function for call to ‘OffsetButtonsWidget::OffsetButtonsWidget(const ButtonLook&, const char [9], int, int)’
   RadioOffsetButtons(bool active_freq):OffsetButtonsWidget(UIGlobals::GetDialogLook().button, "%.0f KHz", 5, 1000),set_active_freq(active_freq) {}
                                                                                                                                               ^
In file included from src/InfoBoxes/Panel/RadioEdit.cpp:26:
./src/Widget/OffsetButtonsWidget.hpp:46:3: note: candidate: ‘OffsetButtonsWidget::OffsetButtonsWidget(const ButtonLook&, const TCHAR*, double, double)’
   OffsetButtonsWidget(const ButtonLook &_look, const TCHAR *_format,
   ^~~~~~~~~~~~~~~~~~~
./src/Widget/OffsetButtonsWidget.hpp:46:3: note:   no known conversion for argument 2 from ‘const char [9]’ to ‘const TCHAR*’ {aka ‘const wchar_t*’}
./src/Widget/OffsetButtonsWidget.hpp:39:7: note: candidate: ‘constexpr OffsetButtonsWidget::OffsetButtonsWidget(const OffsetButtonsWidget&)’
 class OffsetButtonsWidget : public NullWidget, private ActionListener {
       ^~~~~~~~~~~~~~~~~~~
./src/Widget/OffsetButtonsWidget.hpp:39:7: note:   candidate expects 1 argument, 4 provided
./src/Widget/OffsetButtonsWidget.hpp:39:7: note: candidate: ‘constexpr OffsetButtonsWidget::OffsetButtonsWidget(OffsetButtonsWidget&&)’
./src/Widget/OffsetButtonsWidget.hpp:39:7: note:   candidate expects 1 argument, 4 provided
```

**Pull request merged**
