### PR TITLE
Ticket 3930 - Task Editor Crashes

### PR DESCRIPTION
**Pull request by Exadios**
This patch addresses Ticket 3930. A valgrind trace is attached to that ticket. A core file is available on request.

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Please write better commit messages. Yours doesn't explain anything at all. And "Ticket 3930" doesn't need to be present so prominently, because nobody will ever look it up; and even if, GitHub (or this repository on GH) may not exist anymore.
And don't bloat your commit numbers by separating the NEWS update and the bug fix. This belongs in one commit because it's one single change.

**Comment by Exadios** [comment]
> Please write better commit messages. Yours doesn't explain anything at all. And "Ticket 3930" doesn't need to be present so prominently, because nobody will ever look it up; and even if, GitHub (or this repository on GH) may not exist anymore.
> And don't bloat your commit numbers by separating the NEWS update and the bug fix. This belongs in one commit because it's one single change.

I thought you may want to cherry pick the commits.

**Comment by Exadios** [comment]
So, I have squashed the commits and improved the commit message.

**Comment by MaxKellermann** [comment]
I don't understand the part of your commit message which says:
```
Ticket 3930: Fixed program aborts.

Ticket 3930: Updated NEWS.

Ticket 3930: Updated AUTHORS.
```

**Comment by Exadios** [comment]
Fixed.

**Comment by Exadios** [comment]
> Please write better commit messages. Yours doesn't explain anything at all. And "Ticket 3930" doesn't need to be present so prominently, because nobody will ever look it up; and even if, GitHub (or this repository on GH) may not exist anymore.
> And don't bloat your commit numbers by separating the NEWS update and the bug fix. This belongs in one commit because it's one single change.

We (in our professional context) put everything to do with a project within the project tree - and this includes our tickets. That is our tickets exist within the projects git repository. So, if the repository moves, the tickets move with it.

May I suggest that this structure be considered for XCSoar?

**Comment by Exadios** [comment]
Could someone review this PR please?

**Comment by MaxKellermann** [comment]
This PR was based on v6.8.x but you asked to merge it into master.

**Comment by Exadios** [comment]
I don't understand. I don't think I asked to merge it into any branch. I based it on v6.8.x because its a bug fix - not a new feature.

**Comment by MaxKellermann** [comment]
Yes you did, when you created the PR. Maybe you didn't pay attention to the HTML form and just left the default value.

**Comment by Exadios** [comment]
OK. I must have breezed right by that item. Thanks for the info.

**Pull request merged**
