### PR TITLE
V6.8.x

### PR DESCRIPTION
**Pull request by August2111**
Brief summary of the changes
----------------------------

Related issues and discussions
------------------------------

### CODE REVIEW

**Comment by August2111** [comment]
Hopefully I have done this correctly
August

**Comment by lordfolken** [comment]
Did you mean to close this pr?

**Comment by August2111** [comment]
Maybe I understand the 'Close' wrong: I want to insert this changes from kedder not only inserted in the master branch, this should also be done in branch v6.8.x too. Unfortunataly I'm not so familar with this git procedure...

**Comment by kedder** [comment]
@August2111 right now your change does not compile. See the result of circleci build. Also, this probably means you didn't try to compile and run it yourself. Make sure it compiles and actually works as expected.

**Comment by MaxKellermann** [comment]
You added the sentence "Solve the conflict" to the first commit message, what does that mean?
The commits are in the wrong order.
Fixup commits for known-bad commits in the same PR are not acceptable. Get the cherry-pick order right, and the problem will disappear.

**Comment by MaxKellermann** [comment]
Oh and fix your git configuration. Author/committer is wrong.

**Comment by August2111** [comment]
Sorry, it was my fault. I compiled and checked it in a previous state - now the code seems to be better - and is running on my OpenVario

**Comment by August2111** [comment]
Unfortunately I put the commits from kedder in the wrong order - maybe this led to the compile error... The description for this PR is mainly in the 2nd commit - with the wish, to do the same things in the branch v6.8.x too. (This issue is solved in the master branch, but not in v6.8.x)

**Comment by August2111** [comment]
Ok, I solved my git configuration too ;-)

**Comment by kedder** [comment]
@August2111, generally you want to avoid fixup commits, such as bf4cc75c87303bf60a731ddf6a03d58157d08871, in the PRs. The right way to fix it is to put the original commits in the right order. You can do that by resetting your branch back to `6.8.x` (see `git reset --help`), and then reapplying the commits in the right order (see `git cherry-pick --help`).

**Comment by August2111** [comment]
@Kedder Thanks for your help! Because I have a better understanding of the git(hub) workflow now, I will delete/close this PR and create a new one with a new (fork) branch 'linux-orientation_6.8' like your pr branch for exactly this workflow - and a better description for this... Unfortunately I need a little bit time for testing on my OpenVario device (the baking of a new image is broken now) before I will start with the new PR!

**Comment by August2111** [comment]
This pr can be close with the new pull request #491!

**Pull request closed without merging**
