### PR TITLE
Icons update, ViewBox addition

### PR DESCRIPTION
**Pull request by MikeBravo15**
Brief summary of the changes
----------------------------

Unification of icon size to 26x26px where aplicable. Optimization of graphics, removed not visible geometry, added VievBox for correct sizing. Menu and Mode icons extended to the limits to make them as big as possible (no border margin). Waypoint icons are referenced via this Naviter document - https://downloads.naviter.com/docs/SeeYou_CUP_file_format.pdf . Can contribute to #1116, #1130

Related issues and discussions
------------------------------

Can contribute to #1116, #1130

### CODE REVIEW

**Comment by MikeBravo15** [comment]
Sorry for mess, I am hopeless in GitHub

**Comment by MikeBravo15** [comment]
I decided to work further on the icons and also convert all of them to standard format 32x32px. Also if anybody can hint me why they fail the macos build and if it can be solved by manipulating the graphics, I would be grateful. Consider this a draft

**Comment by Scumi** [comment]
The macos build fail is not caused by your PR. Happens for everyone currently. See #1133.

**Comment by ulipo** [comment]
If needed I can help with icons, I have some sort of expertise in that kind of drawings, just drop me a line.

**Pull request closed without merging**
