### PR TITLE
Add missing packages to developer manual.

### PR DESCRIPTION
**Pull request by sbrodehl**
Adds `quilt` and `glm` package to compile instructions (_2.3.1 Compiling for Linux/UNIX_).

### CODE REVIEW

**Comment by MaxKellermann** [comment]
glm is not necessary; it's included as a git submodule.

**Comment by lordfolken** [comment]
Have a look at https://github.com/XCSoar/XCSoar/blob/master/ide/provisioning/install-debian-packages.sh
and please add any missing packages to the manual

**Comment by MaxKellermann** [comment]
Fold those two patches. The first one is wrong, and I don't want to merge a commit when we already know it's wrong.
Rule of thumb: if your PR needs a text, then your commit message is bad. This PR has text.

**Comment by sbrodehl** [comment]
I checked the source files again, and it looks like everything is fine.
Section _2.2 Requirements_, together with section _2.3.1 Compiling for Linux/UNIX_ lists all needed packages for Linux

But, reading the [v6.8.11 XCSoar-developer-manual.pdf](http://download.xcsoar.org/releases/6.8.11/XCSoar-developer-manual.pdf) it turns out that the PDF was build on August 17, 2018!

So, the only thing to do is to build an up-to-date version of the developer manual and publish it, I guess?

Sorry for the confusion! :-/

**Pull request closed without merging**
