### PR TITLE
LocalPath: Android - Use Android/media/ directory for XCSoar's Data

### LINKED ISSUE #992: XCSoarData dir not accessible due to scoped storage policy of Android 11
While testing I came across not being able to access the XCSoarData directory any more after completely uninstalling and reinstalling XCSoar binary on Android.

It seems to be due to the changed storage policy by Android 11.
See here: 
https://developer.android.com/training/data-storage/use-cases

The xcsoar code mentions in LocalPath.cpp
https://github.com/XCSoar/XCSoar/blob/970470f3ab2529e27200a19306d767348a712c34/src/LocalPath.cpp#L249
>         /* the "legacy" external storage directory is writable (either
>            because this is Android 10 or older, or because the
>            "preserveLegacyExternalStorage" is still in effect) - we
>            can use it */

However that only seems to be true if there is still an old installation of XCSoar that is merely updated. For a complete new install or reinstall. XCSoarData is no longer available.

> Note: If you set preserveLegacyExternalStorage to true, the legacy storage model remains in effect only until the user uninstalls your app. If the user installs or reinstalls your app on a device that runs Android 11, then your app cannot opt out the scoped storage model, regardless of the value of preserveLegacyExternalStorage.

Is there anyway around that? Personally I hope there is, since I would hate losing my whole data directory just by accidentally uninstalling XCSoar.
If there is no way around that and scoped storage is the new way eventually, this should be made more visible, to avoid confused users.

### LINKED ISSUE #1524: Android 14: not able to copy airspace and waypoint files into the XCsoar folder
XCSoar versions having the problem
On Android 14 it is not possible to copy something into Android/data/org.xcsoar/files because this folder is blocked from Android

 7.42

It worked on Android 13

System information
Android 14, Xiaomi 14

Expected behavior
Would like to be able to copy WP files and Airspace

### PR DESCRIPTION
**Pull request by lordfolken**

### CODE REVIEW

**Comment by lordfolken** [comment]
Merged

**Comment by zinuzoid** [comment]
Do we need to provide the migration part?

Imagine the user just upgrade to new APK and suddenly all their config is disappeared?

**Comment by zinuzoid** [comment]
Do we need to provide the migration path?

Imagine the user just upgrade to new APK and suddenly all their config is disappeared?

**Comment by lordfolken** [comment]
This could be indeed a problem for the jet edition. 
XCSoar itself anyway has now new signature keys, so it won't upgrade. Except maybe the F-droid release.

**Comment by lordfolken** [comment]
@zinuzoid i hacked something together. Can you test and put into a final form? https://github.com/lordfolken/XCSoar/commit/7e387c3d13935bfb23836ba260091b5b2e4e5be3

**Comment by lordfolken** [comment]
Lets continue in #1544 @zinuzoid

**Pull request closed without merging**
