### PR TITLE
TerrainRenderer: new ramp "Black"  #123

### PR DESCRIPTION
**Pull request by fberst**
Brief summary of the changes
----------------------------

Related issues and discussions
------------------------------

### CODE REVIEW

**Comment by MaxKellermann** [comment]
What's the point of that? This wastes CPU for rendering terrain, drains battery, only to make every pixel black.

**Comment by fberst** [comment]
it's for OLED Displays, on these black pixels are off which should reduce the power consumption of the display

https://github.com/XCSoar/XCSoar/issues/123

I can see the point with the waste of CPU performance, but didn't take that into account with the ridiculous overpowered smartphones we have today, sorry....

**Comment by MaxKellermann** [comment]
> the base color would be black [...] and the terrain would be lighter shades of gray/white

That's not what this PR does - it's all black without any gray/white. It effectively makes the terrain renderer result invisible.

**Comment by fberst** [comment]
here a screenshoot:
Bildschirmfoto vom 2020-10-18 19-10-03

It's dark, but far away from all black and turning invisible, i admit that i don't understand why.
Also why do we already have a "white" ramp? Following the logic this should turn everything white, effectively disabling the rendering of the terrain, that would be the same as turning the terrain off in the settings, which would be also complete pointless.

**Comment by MaxKellermann** [comment]
This is with hill shading. The sunny side gets somewhat gray (auto-calculated "sunny" color, a bit lighter than black), but the other side stays black, because it doesn't get blacker than black.
Is this shade of gray really visible on real screens during a flight, when the sun shines on the display?
... and just look at the black labels on black background - XCSoar just isn't ready for this color scheme.

**Comment by fberst** [comment]
ok, i think we should close this pull request for now,,,

**Pull request closed without merging**
