### PR TITLE
Fixed compatibility with ImageMagick v7

### PR DESCRIPTION
**Pull request by yorickreum**
ImageMagick v7 was throwing `WARNING: The convert command is deprecated in IMv7, use "magick"` during compilation, updated the `build/imagemagick.mk` file to obey the new syntax.

### CODE REVIEW

**Comment by yorickreum** [comment]
Sadly, seems to cause trouble on Linux since ImageMagick v7 can not be installed via apt (yet).
On macOS with homebrew, this is default by now.

**Comment by lordfolken** [comment]
You could variabelize it and set it depending on target.

**Comment by yorickreum** [comment]
> You could variabelize it and set it depending on target.

Okay.

**Comment by yorickreum** [comment]
I could not reopen this PR for some reason, hence I created https://github.com/XCSoar/XCSoar/pull/1747 instead.

**Pull request closed without merging**
