### PR TITLE
Backport BLE type/name fix to 6.8.x

### LINKED ISSUE #149: Reconnect to BLE serial interface fails after Android Bluetooth restart
Connecting a BLE serial interface device to XCSoar works, and the device will automatically be reconnected while that device's information remains in the Android Bluetooth cache. If the Bluetooth  system is restarted (e.g. turn Bluetooth off and on) or the phone is rebooted, the systems's cached information  about the device is lost. Then when BluetoothHelper#connect() is called with the MAC address of the device, it is assumed to be a legacy (RFCOMM) device and a connection attempt is made using legacy Bluetooth calls. This fails.

A side effect of this is that the device name is also lost, so it is displayed with the MAC address only in the device list.

So two changes are needed:

1) record the device type (BLE vs RFCOMM)
2) cache the device name for display purposes

Item 1) could be achieved by adding a new device type in DeviceConfig::PortType and changing the interface to the Android code. This won't solve 2)

An alternative would be to encode the device type and name into the MAC address string. This would require a change to the way the mac address is stored in the Config object.

Another alternative is to maintain persistent state for the device in the Android specific code, for example using a SharedPreferences instance or a file in the XCSoar directory. This would map each MAC address to a device type and name. This would not require any change to the non-Android code. The SharedPreferences option is easy, but has the drawback that copying the XCSoar default data directory to a new device would not transfer that information. Creating a file in the XCSoar directory would require knowledge of where that is, and a cursory inspection did not reveal any existing mechanism for Android Java code to access that in XCSoar.

My plan is to implement the last alternative using a SharedPreferences instance. Comments?

### PR DESCRIPTION
**Pull request by clydebarrow**
Fixes #149 for V6.8.x

### CODE REVIEW

**Comment by Turbo87** [comment]
just for understanding, this is the same as #151 but for the `v6.8.x` branch, correct?

**Comment by clydebarrow** [comment]
Correct, same fix.

**Comment by Turbo87** [comment]
okay, thanks for the clarification. I have enough permissions here to merge, but I'm not confident enough in the code at the moment to actually be comfortable doing so.

@MaxKellermann can you have a look?

**Comment by MaxKellermann** [comment]
Ah, I see, so this is a backport of some unmerged code.
We shouldn't merge both PRs - if there is a bug that needs to be fixed in both branches, it should be merged to stable first, and later stable will be merged into master.

**Comment by MaxKellermann** [comment]
I think your approach is a fragile solution, because it moves the decision which protocol to use to a cache, when it should really be configuration.
And I don't like that this commit tries to solve two problems at once: caching the name and fixing a connection problem.

**Comment by clydebarrow** [comment]
I'm not sure that I understand the distinction here between cache and configuration. Are you suggesting the information should be stored elsewhere, i.e. in an existing datastore? It has to be stored somewhere.

**Comment by MaxKellermann** [comment]
Huh, it was you who designed this distinction, and now you don't know it?
Configuration: XCSoar's profile.
Cache: your `class BluetoothCache`

**Comment by clydebarrow** [comment]
The other approach I had considered which would address your concerns is to add a new type to Device/Config.hpp - currently RFCOMM is used for both legacy Bluetooth and Bluetooth LE. If a new type was added, e.g. BLE, to be used for BLE devices, and RFCOMM used only for legacy Bluetooth serial devices, this would solve the problem since there would be no ambiguity as to which type of Bluetooth device was associated with a port. This will be a much more extensive changeset though.

**Comment by MaxKellermann** [comment]
That sounds like a good idea. BLE devices are not RFCOMM, after all. Note that XCSoar's usage of BLE is not "pure" BLE either, it's a protocol on top of BLE.

**Comment by clydebarrow** [comment]
Quite true - with that in mind it might be better to choose a name that reflects the specific GATT characteristic that is used in the current implementation. It's a proprietary UUID, not part of an official GATT service, best as I can tell it originates from a device called an HM-10, so the device type could perhaps be BLE_HM10.

**Comment by MaxKellermann** [comment]
5 months later, there is still no usable code, so closing this PR.

**Pull request closed without merging**
