### PR TITLE
Icons update

### PR DESCRIPTION
**Pull request by MikeBravo15**
Unification of icon size to 32x32px for Menu/Mode icons and to 22x22 for Map icons (diff. size for potential future development). Optimization of graphics, removed not visible geometry, added ViewBox for correct sizing. Waypoint icons are referenced via this Naviter document - https://downloads.naviter.com/docs/SeeYou_CUP_file_format.pdf .Added icon template file. Can contribute to #1116, #1130, ViewBox importance see in #982

### CODE REVIEW

**Comment by lordfolken** [comment]
@XCSoar/kobo-team could someone test this on their kobos? 
i tested an android build and things looked good. 
Trying openvario now...

**Comment by lordfolken** [comment]
The main issue is the flight status icon in the lower left. Its just too small to make out.

**Comment by ubx** [comment]
I tested the Libra 2, it looked good, but I noticed that on Kobos, the flight status icon in the lower right is too small. This problem was already in v7.28. I think we should create a new issue to address it.

**Comment by lordfolken** [comment]
Danke.
@ubx can you check for #1026  on the libra2?

**Comment by ubx** [comment]
> Danke. @ubx can you check for #1026 on the libra2?
No icons at all, just text labels.

**Comment by lordfolken** [comment]
> > Danke. @ubx can you check for #1026 on the libra2?
> > No icons at all, just text labels. I can't see any icons on Linux, Kobo, or Android.

Oh sorry its  a configuration option:
Look->Screen Layout (expert)
Tab dialo style set to icons

**Comment by MikeBravo15** [comment]
I consider 22x22 px size for icons too small for high DPI screens. Can you please also check my test build mentioned at #1116 for bigger menu/mode icons and report back? Thank you very much

**Comment by ubx** [comment]
Another option I missed. The icons are actually visible, although they might be a bit small.
task-manager

**Comment by lordfolken** [comment]
So the discussion about icon sizing should go here: https://github.com/XCSoar/XCSoar/issues/1116

I like about this PR that all the icons are correctly sized, that the viewport is fixed etc. This gives us a good basis for introducing changes.

**Pull request merged**
