### PR TITLE
Weather/Skysight: Basic integration of Skysight weather forecasts (WIP)

### PR DESCRIPTION
**Pull request by krankenreif**
This is (another) WIP PR for the Skysight integration. There are a lot more things that can be refactored but it I wanted to attract a few other interested people here that may want to help.

All the code is based on the initial integration by @jfwells https://github.com/XCSoar/XCSoar/pull/182 and some more work done by @CazYokoyama  https://github.com/XCSoar/XCSoar/pull/298

There also are a lot of comments and discussions in these two PRs and not all faults have been fixed yet.

### CODE REVIEW

**Comment by MaxKellermann** [comment]
I welcome this effort, but are you aware that the way you manage your PR branch, it's impossible to review it?

**Comment by krankenreif** [comment]
I hope I got what you meant by that... This should now be more accessible.

**Comment by MaxKellermann** [comment]
No. The "initial SkySight integration" commit doesn't even compile. All commits must be buildable, to allow `git bisect`.
Fixup commits for previous commits in the same PR are not acceptable.
Before I start a review (after this PR has been sanitized): are you sure you addressed *all* review comments in the previous PRs?

**Comment by krankenreif** [comment]
Okay, thank you for the feedback. These commits are all buildable now. I have not (yet) addressed all comments made to the other PRs. Some dynamic allocations could be static, dumb pointers should (mostly) be smart ones, signed ints for array lengths should be unsigned and so on. Maybe someone wants to contribute to this and help me implement these changes or maybe also advance the UI (for example make the time of the forecast changeable).
When all of the ToDos I have in mind have been fixed, I will mark the PR as ready for review.

**Comment by MaxKellermann** [comment]
Nearly a year without progress. Let's reopen this when the code is ready.

**Pull request closed without merging**
