### PR TITLE
add Arcus M and Silence E78 polars

### PR DESCRIPTION
**Pull request by fberst**
- add Arcus M polar, data provided by [silverstate64](https://github.com/silverstate64) in issue #1070
- add Silence E78 polar, duplicate to pull request #1046, because original author didn't respond to fix his commits

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Do we really need separate Arcus and Arcus M polars?

**Comment by MaxKellermann** [comment]
If it's only about usability, maybe yes, but then we shouldn't have two polars in the source code, but instead derive one from the other (at compile time). Redundant data is always a maintenance burden.

**Comment by mlep** [comment]
Indeed, not being a programmer, my comment was only about usability.

**Comment by hjr** [comment]
Your provided Arcus M polar is slightly different to what I got from Bernd Weber. Where do you have the polar from? Otherwise we introduced the empty weight attribute to the plane configuration. There is now merely no good reason to have two polars in the store, just because of mass differences. Eg we removed all two seater duplicates because of that.
ArcusPolars

**Comment by hjr** [comment]
You might want to split the pull request of both polars to get the Silence in straight forward. (Or strip the Arcus M commit)

**Comment by fberst** [comment]
I agree, we should merge the silence polar and close this pull request.

**Pull request merged**
