### PR TITLE
finally enable -Wunused

### PR DESCRIPTION
**Pull request by fberst**
As suggested by max i worked on enabling the -Wunused compiler-option.

Not quite sure about this. Tell me if i should split it into more smaller commits.

### CODE REVIEW

**Comment by MaxKellermann** [comment]
```
In file included from test/src/KeyCodeDumper.cpp:27:
test/src/Main.hpp:198:14: error: unused parameter 'argc' [-Werror,-Wunused-parameter]
int main(int argc, char **argv)
             ^
test/src/Main.hpp:198:27: error: unused parameter 'argv' [-Werror,-Wunused-parameter]
int main(int argc, char **argv)
                          ^
test/src/KeyCodeDumper.cpp:69:31: error: unused parameter 'p' [-Werror,-Wunused-parameter]
  bool OnMouseDown(PixelPoint p) override {
```
Lots of warnings remain.

**Comment by fberst** [comment]
Build-Target and options? 
I compiled it for UNIX / ANDROID / PC / KOBO with DEBUG=y and it worked for me without errors

**Comment by MaxKellermann** [comment]
Build target `everything` - I assume you omitted all those test/debug programs.

**Comment by fberst** [comment]
> Build target `everything` - I assume you omitted all those test/debug programs.

Ok that makes sense, i didn't think about the test programs, i will go through these and fix this

**Comment by MaxKellermann** [comment]
And: sometimes, it's less ugly to just remove the parameter name instead of adding `[[maybe_unused]]` (oh, how ugly is C++ ...)
That has a nice side effect; it enforces that the parameter is really not used (because there's no name it could be referred to).

**Comment by fberst** [comment]
> And: sometimes, it's less ugly to just remove the parameter name instead of adding `[[maybe_unused]]` (oh, how ugly is C++ ...) That has a nice side effect; it enforces that the parameter is really not used (because there's no name it could be referred to).

that's the next step, after i identified and marked all those places in the code i can start removing some of these parameters

**Comment by MaxKellermann** [comment]
No, not remove parameters; remove the parameter **name**.
```
void Foo(int unused_arg) {} // screams warning at you
void Foo([[maybe_unused]] int unused_arg) {} // ugly
void Foo(int) {} // not ugly, but why is this parameter here in the first place?
```
Of course, you can remove unused parameters; but sometimes, you cannot, e.g. for virtual overrides, or if the parameter is used in an `assert()`.

**Pull request merged**
