### PR TITLE
src/Dialogs/Settings/Panels/PagesConfigPanel.cpp : Typos corrections in help texts

### PR DESCRIPTION
**Pull request by MikeBravo15**
Removal of double spaces at the the end of  the first sentence. Added commas at the last sentences of the help text

Brief summary of the changes
----------------------------

Minor typo corrections in helptexts

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Bad commit message.

**Comment by MikeBravo15** [comment]
Updated

**Comment by lordfolken** [comment]
He meant the "updated PagesConfigPanel" please stick to our format of <File/Component>: <what was changed> \n <longer description if needed>

**Comment by MaxKellermann** [comment]
Any commit message that begins with "Update <filename>" is bad. I won't even look at the diff here.

**Comment by lordfolken** [comment]
You misunderstand. Not the pr text. The commit message. .

**Review by lordfolken — CHANGES_REQUESTED** [review]
The pr title should be the commit message. Here it just says updated xxxx. The or text, discussion and title is lost once the commit is merged.

**Comment by MaxKellermann** [comment]
Text entered into GitHub doesn't matter. Editing on GitHub doesn't matter. Nothing in GitHub matters. All that matters is what's stored in git.

**Comment by MikeBravo15** [comment]
I am not able to change the title in my pull request, so I close this now and create new attempt

**Comment by MaxKellermann** [comment]
> I am not able to change the title in my pull request, so I close this now and create new attempt

noooooooooooo!

**Comment by lordfolken** [comment]
go to your git repo
do a 
`git commit --amend`
This will edit your current commit and display the commit message again. 
* Change the commit message and save. 
* Then you force push the branch with git push --force

**Comment by lordfolken** [comment]
This will update your current git branch and hence your pull request.
I hope that was clearer. :-)

**Pull request closed without merging**
