### PR TITLE
Ticket 1687 on master

### PR DESCRIPTION
**Pull request by Exadios**
This branch adds AAT turn point type 'Variable Sector'. See ticket 1687 for context.

### CODE REVIEW

**Comment by Turbo87** [comment]
This PR seems to contain a lot more than just a new turnpoint type 🤔

**Comment by Exadios** [comment]
Are you referring to commits such as https://github.com/XCSoar/XCSoar/pull/127/commits/1f03cb00700bae50913573804d355cfde3c98df6? If so them these commits are the result of rebases from the upstream master.

**Comment by Turbo87** [comment]
yes, commits like that. they shouldn't appear on this branch. the branch should only contain the relevant commits for this change.

**Comment by Exadios** [comment]
OK. I was under the impression that you wanted the feature branches to be rebased. As I understand it these should drop out in the merge.

**Comment by Turbo87** [comment]
> I was under the impression that you wanted the feature branches to be rebased.

that is correct, but you should only rebase your own commits, not any irrelevant commits. you can use `git log` or `gitk` to check how the branch looks like and `git rebase --interactive` to throw away irrelevant commits.

**Comment by Exadios** [comment]
OK. I think I see what has happened. There's been a reset upstream. The actual rebase went OK but the repository Exadios/XCSoar then became out of sync. Instead of forcing the push to that repository I merged from it. This put my local copy and my remote repository in sync again but re introduced the commits that had been reset out upstream.

I'll fix it up.

**Comment by MaxKellermann** [comment]
Hmmm.... "Ticket 1687 preparation for upstream push." this PR looks like a mess.

**Comment by MaxKellermann** [comment]
Is this PR going anywhere? In the current state (28 confusing commits) it cannot be reviewed.

**Comment by MaxKellermann** [comment]
Will be reopened after this branch has been sanitized.

**Pull request closed without merging**
