### PR TITLE
Issue 81: Fix UNIX build.

### PR DESCRIPTION
**Pull request by Exadios**

### CODE REVIEW

**Comment by Turbo87** [comment]
Can you rebase this on the latest `master` of `v6.8.x` branch?

**Comment by Exadios** [comment]
I don't understand. What's the "master of v6.8.x branch"?

**Comment by Turbo87** [comment]
oh sorry, that was a typo. I meant `master` **or** `v6.8.x` branch.

**Comment by Exadios** [comment]
That's a relief. I thought I was missing something fundamental. :)

I can see what I've done - I've branched from that tag. I'll fix it up next time I'm down at the club.

On a related matter, I'm mightily confused about the git work flow you are using for this project. Could you say a few words about this. If so I'll write something up for the Developers' Manual. I doubt that I'm the only person that's confused.

**Comment by Turbo87** [comment]
> On a related matter, I'm mightily confused about the git work flow you are using for this project. Could you say a few words about this. If so I'll write something up for the Developers' Manual. I doubt that I'm the only person that's confused.

@MaxKellermann used to run a dedicated git server for this project, but a few months ago decided to use GitHub for this project instead. Unfortunately since then he has been relatively quiet so I'm not sure about his thoughts on this, but I can tell you what I think ;)

The `master` branch is the main development branch where new features should be developed on (currently targeting a v7.0.0 release). The `v6.8.x` is the current stable branch where bugfixes for the v6.8 release line should be done.

The docs still mention submitting patches to the mailing list, but I think it should also be fine to open pull requests here against either of those two branches. Your feature branches (the ones that you open PRs for) should be regularly rebased on top of the target branch to make sure that they are up-to-date and don't break anything else when merged.

Do you have any other questions?

TBH our main problem right now is that Max seems inactive and I haven't done any C++ in years so I'm not capable of reviewing any complex PRs. Would love to get help :)

**Comment by Exadios** [comment]
Yes, I noted the git repository move. I know that Max has some concerns about putting the repository on a third party site. And I appreciate those concerns. After all, if GitHub was to "go rogue", it would not be the first time this has happened. But the main 'asset' of the XCSoar project is the git repository itself and that remains firmly in the hands of the many developers.

I thought that the work flow must have been as you describe but, after scanning NEWS.txt and the commits, I saw many items that made me think it was otherwise. The way you have described it sounds like a plan to me. When I get a chance I'll write some words in the Developers' Manual along those lines.

I'll also write something about the GitHub methods of submitting patches.

I've never used GitHub before (other than a bare git repository) so I've used these last few patches to test the procedure. I have a couple of larger patches which I will present in a few months. One is rebased on the v6.8.x branch because I have been trying to get people to test it out (harder than you might think) and I wanted to give them a reasonably stable edition to use.  I will move this patch over to master before I send it to you. The other is still being written and is based on master. I will keep them rebased on the top of your master.

I would not describe myself as a C++ guru - especially when it comes to the later editions - c++/11/14/17 but I can help out in any whey possible.

**Comment by kerel-fs** [comment]
@Exadios What does this PR fix, and how? Can you please rebase it to only contain the according commit(s) and explain this in their commit message?

If this is really not possible to you, you can alternatively explain it here and link the according commits?

**Comment by Exadios** [comment]
Issue 81 has been closed. So this pull is, likewise, closed.

**Pull request closed without merging**
