### PR TITLE
Fix several bugs related to KRT2 remote control

### PR DESCRIPTION
**Pull request by roeles**
- Fix a bug where the frequency is re-set to a previous value after using the infobox to change it.
- Enable exchanging of frequencies from the KRT2
- Fix offsetting of frequencies, skip invalid 8.33kHz channels
- Clamp MHz values in KRT2 driver to values specified in the KRT2 user manual

### CODE REVIEW

**Comment by roeles** [comment]
@fb FYI

**Comment by fb** [comment]
I was able to test it today (c3cfd23). My KRT2 is "Vers. 8.2" (with dark color display).

- on startup, the correct frequencies will appear in the infoboxes
- set standby/active frequency works as expected
- I can play around on the KRT and the result in the UI will stay the same as on the radio

that means #322 is resolved. :+1: 

Regarding #321: Offsetting frequencies via infoboxes is also working (so technically, it's also fixed).

Now set standby to 118.00 and offset by -5 kHz. The infobox will show 117.990, the KRT will be set to 118.990.
Swapping frequencies on the KRT will put the 117.990 into the active frequency infobox.

Could be sufficient if KRT2Device::PutFrequency(… 117.990 …) returned false?

**Comment by roeles** [comment]
Noticed that as well. The clamping is wrong (should be done on the entire
freq and not just on the mhz), but since there is no feedback mechanism
this is difficult.
Since in theory multiple radios might be connected and one could succeed
and another could fail, it is hard to define correct behavior.
Perhaps the driver should store the last successfully set frequency and
send that back as if it was sent by the radio with an stx frame.

**Comment by roeles** [comment]
I'm going to close this request for now:
- The MHz check really belongs in RadioFrequency. The frequencies that KRT2 allows are the aviation voice frequencies. So, in the context of gliding (and thus XCSoar), anything outside of 118-136MHz is invalid.
- I had to solve a merge conflict, which results in an extra commit. I don't like that.

**Pull request closed without merging**
