### PR TITLE
Updated README.rst

### PR DESCRIPTION
**Pull request by satvikmittal638**
Brief summary of the changes
----------------------------

Related issues and discussions
------------------------------

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Is this a joke?

**Comment by lordfolken** [comment]
Probably didn't know what he was doing. :-) Lets see.

**Comment by dernatsch** [comment]
Looks like [Hacktoberfest spam](https://blog.domenic.me/hacktoberfest/)

**Comment by MaxKellermann** [comment]
Oh no!
Fortunately, PRs with a description "Updated XY" can usually be closed without any review. That's the default commit message generated by GitHub when creating commits with the web interface. All such PRs are doomed to fail.

Shame on @satvikmittal638 for bullshitting us.

**Pull request closed without merging**
