### PR TITLE
Waypoint, Settings: Store home waypoint name instead id in profile.

### LINKED ISSUE #1122: Changing number of markers changes Home field
XCSoar versions having and not having the problem
-------------------------------------------------
tested in v7.28

Expected behavior
-----------------

One can use the marker function to add and remove markers without it to cause the home field to change. 

Actual behavior
---------------

When a marker is added or existing markers are removed, basicly when number of markers changes. Next time you start up XCSoar the home field is different.

Steps to reproduce the behavior
-------------------------------

Start up XCSoar either in fly or sim mode --> add a marker --> close XCSoar --> open XCSoar fly or sim mode and check home field it will be different airfield. (Checking in sim mode is easiest as plane starts at home field).

Do you have any idea what may have caused this?
-----------------------------------------------

From my testing it looks like home field is stored as some kind of list index and markers are added at the top of the list changing all the indices without changing what index is used for home thus changing home field.

Do you have an idea how to solve the issue?
-------------------------------------------

Add markers at bottom of list or different list or store home field by name or coordinate.

### PR DESCRIPTION
**Pull request by ubx**
Fixes changing number of markers changes home field #1122.

Brief summary of the changes
----------------------------
This PR resolves the issue where changing the number of markers caused the home field to change.

Related issues and discussions
------------------------------

Closes #1122

### CODE REVIEW

**Comment by August2111** [comment]
I don't know if I'm wrong, but in my opinion the name of a waypoint doesn't have to be unique, there can be several waypoints with the same name, but they designate different places (e.g. train station, church, airfield,...) You need here necessarily a field with a unique identifier, so the ID is not wrong. The problem here is of course that the ID can change ;-(

**Comment by ubx** [comment]
You are right, I was probably too hasty in providing this solution. Using a unique home waypoint ID would be the proper solution.

**Comment by groundhogxc** [comment]
How about storing the name, altitude and the coordinates together as an ID string (or a hash of these). That should be unique, and if it is not, at least it will point to the right position and, importantly, to the right altitude.

**Comment by ubx** [comment]
Obsolete, fixed in  #1287.

**Pull request closed without merging**
